baseURL = "https://rausr.com/"
enableRobotsTXT = true
languageCode = "en-us"
title = "Random User Recipes"
googleAnalytics = "UA-168547988-1"

[params]
    author = "rausr"
    description = "Graphic design kitchen and creative blog – trends, techniques, and marketing insights."
    accent = "#43414C"
    showBorder = false
    fonts = ["Satoshi", "Inter"]
    paginate = 6
    featuredContent = ["print-design-branding-madness-t3-events-2020", "genz-tiktok-design-trends", "package-design-print-design-pets-probiotics", "various-illustrations"]
    blogThanksText = "Thanks for reading ✌️"
    defaultImage = "/images/default-og.png"

[taxonomies]
  tag = "tags"
  topic = "topics"

[[menu.main]]
    url = "/works/"
    name = "Works"
    weight = 2

[[menu.main]]
    url = "/blog/"
    name = "Articles"
    weight = 3

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 4

[[menu.main]]
    url = "/contact/"
    name = "Contact"
    weight = 5

[[menu.icon]]
    url = "https://instagram.com/rausr_com"
    name = "fa fa-instagram"
    title = "Instagram"
    weight = 1

[[menu.icon]]
    url = "https://www.facebook.com/rausrdotcom/"
    name = "fa fa-facebook"
    title = "Facebook"
    weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

      [markup.goldmark.renderer.linkAttributes]
        rel = "noopener"
        target = "_blank"

# Use Git commit timestamps for lastmod when available
enableGitInfo = true

[frontmatter]
  # preferred order for lastmod
  lastmod = ["lastmod", ":git", "date", "publishDate"]

[sitemap]
  filename = "sitemap.xml"
  changefreq = "weekly"
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "SITEMAP"]

[mediaTypes."application/json"]
  suffixes = ["json"]

[outputFormats.JSON]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = true